### ISSUE TITLE
Freeform intersection

### ISSUE THREAD

**Issue by jgvabo** [equinor/intersection#19]
Should be able to display an intersection of a given path in the plane.

**Comment by farzadfz** [comment]
Will this requirement/issue be already satisfied outside the component via input parameters ?

**Comment by andreabrambilla** [comment]
I don't fully understand what this issue is about. @jgvabo do you mean that data is passed to the component as a "volume" and the intersecting plane should be computed inside the intersection component? If that's the case, we should close this issue as we agreed that feature will be implemented outside the component. Otherwise, could you please elaborate?

**Comment by jgvabo** [comment]
The feature is to display an intersection along an arbitrary path in the xy plane, not only along wellpaths. Should be quite straightforward to implement.

**Comment by jgvabo** [comment]
As @farzadfz mentions, if the intersecting path is an input parameter to the component - then this is already solved.

**Comment by andreabrambilla** [comment]
👍
